//! ytfast: a native YouTube Music client. See docs/SPEC.md.

pub mod account;
#[cfg(feature = "egui")]
pub mod app;
pub mod auth;
pub mod backend;
#[cfg(feature = "egui")]
pub mod control;
#[cfg(feature = "egui")]
pub mod covers;
#[cfg(feature = "egui")]
pub mod derived;
pub mod desktop;
#[cfg(feature = "e2e")]
pub mod e2e;
pub mod equalizer;
pub mod heat;
#[cfg(feature = "egui")]
pub mod icons;
pub mod innertube;
pub mod links;
pub mod lyrics;
pub mod model;
pub mod mpris;
pub mod mpv;
pub mod notify;
#[cfg(feature = "egui")]
pub mod palette;
pub mod parse;
pub mod paths;
pub mod resolver;
pub mod searches;
pub mod settings;
pub mod single_instance;
#[cfg(feature = "egui")]
pub mod theme;
pub mod tray;
#[cfg(feature = "egui")]
pub mod ui;
